do_train = true
do_eval = true
do_test = true
# dataset_names = ["qnli", "mnli", "trec_coarse", "dbpedia", "sst2", "yelp_polarity"]
dataset_names = ["trec_coarse_text"]
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
per_device_eval_batch_size = 32
per_device_train_batch_size = 32
report_to = "wandb"
wandb_project = "arithmetics"
max_source_length = 256
split_validation_test = true
output_dir = "saves/prompt_tuning"
predict_with_generate = true
evaluation_strategy = "steps"
save_strategy = "steps"
logging_strategy = "steps"
eval_steps = 100
save_steps= 100
logging_steps = 100
load_best_model_at_end = true
metric_for_best_model = "eval_average_loss"
greater_is_better = false
save_total_limit = 1
task_type = "SEQ_2_SEQ_LM"
num_virtual_tokens = 50
weight_decay = 1e-5
warmup_steps = 500
num_train_epochs = 50
learning_rate = 0.3
origin_prompts = ["origin_0", "origin_1", "origin_2", "origin_3", "origin_4", "origin_5", "origin_6", "origin_7", "origin_8", "origin_9"]
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500